"""add account balance

Revision ID: 2038594f8fe4
Revises: c21e69e01cf3
Create Date: 2026-08-29 10:35:20.191052

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2038594f8fe4"
down_revision: str | Sequence[str] | None = "c21e69e01cf3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("current_balance", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column("accounts", sa.Column("balance_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "balance_date")
    op.drop_column("accounts", "current_balance")
    # ### end Alembic commands ###
