"""add transaction category

Revision ID: c21e69e01cf3
Revises: b5e2d3c4f5a6
Create Date: 2026-08-22 09:48:28.320922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c21e69e01cf3"
down_revision: str | Sequence[str] | None = "b5e2d3c4f5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("category", sa.String(length=125), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "category")
    # ### end Alembic commands ###
