"""add transaction import fingerprint

Revision ID: d10ed3e166ab
Revises: 10913d083d16
Create Date: 2026-08-16 18:14:28.099645

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d10ed3e166ab"
down_revision: str | Sequence[str] | None = "10913d083d16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("import_fingerprint", sa.String(length=64), nullable=False),
    )
    op.create_unique_constraint(
        "uq_transactions_account_import_fingerprint",
        "transactions",
        ["account_id", "import_fingerprint"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_transactions_account_import_fingerprint", "transactions", type_="unique"
    )
    op.drop_column("transactions", "import_fingerprint")
    # ### end Alembic commands ###
